// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbSWSDZuCxXcrx8RiDdUMSSdpNiwQwDFk',
    appId: '1:749184033665:web:a51c42fae97437f38f3e80',
    messagingSenderId: '749184033665',
    projectId: 'tera-app-89912',
    authDomain: 'tera-app-89912.firebaseapp.com',
    databaseURL: 'https://tera-app-89912-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tera-app-89912.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBytsMCzMKW79nCQEGgKbStE9LZwxVAVxE',
    appId: '1:749184033665:android:7d1a6127af46ff9b8f3e80',
    messagingSenderId: '749184033665',
    projectId: 'tera-app-89912',
    databaseURL: 'https://tera-app-89912-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tera-app-89912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV_jghRzQLvjHRZH3vXDPj1re4etmt3Zo',
    appId: '1:749184033665:ios:864812b715f78a4e8f3e80',
    messagingSenderId: '749184033665',
    projectId: 'tera-app-89912',
    databaseURL: 'https://tera-app-89912-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tera-app-89912.firebasestorage.app',
    iosBundleId: 'com.example.tugasBesar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV_jghRzQLvjHRZH3vXDPj1re4etmt3Zo',
    appId: '1:749184033665:ios:864812b715f78a4e8f3e80',
    messagingSenderId: '749184033665',
    projectId: 'tera-app-89912',
    databaseURL: 'https://tera-app-89912-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tera-app-89912.firebasestorage.app',
    iosBundleId: 'com.example.tugasBesar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbSWSDZuCxXcrx8RiDdUMSSdpNiwQwDFk',
    appId: '1:749184033665:web:fc9ca3ebfea3a2498f3e80',
    messagingSenderId: '749184033665',
    projectId: 'tera-app-89912',
    authDomain: 'tera-app-89912.firebaseapp.com',
    databaseURL: 'https://tera-app-89912-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tera-app-89912.firebasestorage.app',
  );
}
